# Generated by Django 5.2.1 on 2025-05-29 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Khoa / Phòng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khoa / Phòng',
                'verbose_name_plural': 'Khoa / Phòng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Tổ chức')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nội dung')),
                ('date', models.DateField(verbose_name='Ngày họp')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Thời gian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm')),
                ('status', models.CharField(choices=[('Đã lên lịch', 'Đã lên lịch'), ('Đang diễn ra', 'Đang diễn ra'), ('Đã kết thúc', 'Đã kết thúc'), ('Bị hủy', 'Bị hủy')], default='Đã lên lịch', max_length=20, verbose_name='Trạng thái')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Chủ trì')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparation_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Người chuẩn bị')),
            ],
            options={
                'verbose_name': 'Cuộc họp',
                'verbose_name_plural': 'Cuộc họp',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('individual', 'Cá nhân'), ('department', 'Khoa/Phòng'), ('group', 'Ban/Đoàn thể')], default='individual', max_length=20, verbose_name='Loại thành phần tham dự')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc tham dự')),
                ('attended', models.BooleanField(default=False, verbose_name='Đã tham dự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_participants', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='meeting_manager.department', verbose_name='Khoa/Phòng')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='meeting_manager.meeting', verbose_name='Cuộc họp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to=settings.AUTH_USER_MODEL, verbose_name='Cá nhân')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participants', to='meeting_manager.organization', verbose_name='Tổ chức')),
            ],
            options={
                'verbose_name': 'Thành phần tham dự cuộc họp',
                'verbose_name_plural': 'Thành phần tham dự cuộc họp',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='meeting_manager.meetingparticipant', verbose_name='Thành phần tham dự'),
        ),
        migrations.CreateModel(
            name='UserAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vai trò')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='meeting_manager.department', verbose_name='Khoa / Phòng')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='meeting_manager.organization', verbose_name='Tổ chức')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Ban/Ngành công tác',
                'verbose_name_plural': 'Ban/Ngành công tác',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalo_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zalo ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('zalo_notification', models.BooleanField(default=True, verbose_name='Nhận thông báo qua Zalo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
        ),
    ]
