# Generated by Django 4.2 on 2025-05-30 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_manager', '0003_notification_meetingminutes_meetingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingfile',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Tên file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingfile',
            name='file',
            field=models.FileField(upload_to='meeting_files/', verbose_name='Tập tin'),
        ),
    ]
